---
# provide path string, where config class generates a fully valid string from it
refractive_index_path_string: ../../refractiveindex.info-database/
# is path string relative to the config file template
# in Python package?
refractive_index_path_is_relative: True
...
